### ISSUE TITLE
Is it possible to subscribe to several topics at the same time

### ISSUE THREAD

**Issue by INTERNALINTERFERENCE** [chkr1011/MQTTnetApp#20]
I wanna subscribe on "$SYS, $SYS/broker" for example. Is it possible to listen all topics at the same time?

**Comment by chkr1011** [comment]
Yes you can add multiple topic filters to a single subscribe request. The builder for the subscribe options supports that as well.

**Comment by chkr1011** [comment]
No this is not yet supported. The question is how to define this in the UI. For now every topic has its own list item. In the next version I will add a storage so that the list items are stored and it is not required to add them again all the time.
