### ISSUE TITLE
The connection is terminated if you don't use the application for about 10 minutes

### ISSUE THREAD

**Issue by INTERNALINTERFERENCE** [chkr1011/MQTTnetApp#22]
Order of my actions:
1. connect to my host
2. subscribe to topics
3. leave the computer for 10 minutes
4. after 10 minutes, the connection is terminated

if I use the app, the connection will never terminated

**Comment by chkr1011** [comment]
Also please open and activate the Packet Inspector and let me know if the broker is sending a DISCONNECT before the connection is closed.

**Comment by INTERNALINTERFERENCE** [comment]
> What exactly do you mean "don't use"? Are you not using your PC by not using Mouse etc. or do you mean that you are not subscribing or publishing in the App only but still working with your PC?

I mean I don't subscribe, publish etc. I run the app and look at incoming messages

**Comment by chkr1011** [comment]
What Broker do you use? 
Which protocol version? 
Keep Alive enabled or 0?

**Comment by INTERNALINTERFERENCE** [comment]
1. my own 
2. tcp 
3. I changed client options builder a little bit so: 
`.WithKeepAlivePeriod( TimeSpan.FromSeconds( int.MaxValue ) );`
I want the application to work endlessly

**Comment by INTERNALINTERFERENCE** [comment]
int.MaxValue - it is about 20+ days 
it seemed to me that this was enough, but, as it turned out, no. [Mqtt explorer](http://mqtt-explorer.com/) works fine with my broker

**Comment by chkr1011** [comment]
Please open and enable the log page and show me the content right before the connection gets closed.

**Comment by chkr1011** [comment]
@INTERNALINTERFERENCE Do you use macOS? If so, we probably found the reason.
