### ISSUE TITLE
Support x509 certificate based authentication

### ISSUE THREAD

**Issue by holance** [chkr1011/MQTTnetApp#37]
Would like the app to support x509 certificate based authentication. Thanks.

**Comment by chkr1011** [comment]
Sure thing. I will create a feature branch for this and add a custom control for loading the certificate including the password. As soon as there is something testable I will let you know. Then you can test it and provide feedback.

**Comment by chkr1011** [comment]
This feature is now implemented and will be available with version 1.6.
