### ISSUE TITLE
[Request] Websocket connection UX

### ISSUE THREAD

**Issue by KiranChinnam** [chkr1011/MQTTnetApp#39]
When selecting 'websocket' as the transport, the port field has no effect, since the host field effectively becomes an 'address field' where you specify the host, port and path all in one. This wasn't immediately obvious to me as a new user, until after some trial and error.

As a suggestion, when the user selects the websocket transport, could the UI disable the port field, and change the host field's label to say 'address'?

**Comment by chkr1011** [comment]
Hi, thank you for your feedback. This is indeed a good point and I will implemented it as you proposed.

**Comment by chkr1011** [comment]
Please checkout the branch and let me know what you think.

**Comment by KiranChinnam** [comment]
I just built from the branch, looks good. 

I think it might flow better if the transport field was before the host field. Something like this: 
![image](https://user-images.githubusercontent.com/15803210/162633640-3655166d-7606-4b7b-8627-89604cd11568.png)

I tried to change it myself, but I lack experience with Avalonia and the fields were just overlapping each other.

**Comment by chkr1011** [comment]
I updated the branch. Please have a look again.

**Comment by KiranChinnam** [comment]
Perfect, exactly what I had in mind! :)
