### ISSUE TITLE
Is it possible to subscribe to several topics at the same time?

### ISSUE THREAD

**Issue by INTERNALINTERFERENCE** [chkr1011/MQTTnetApp#40]
I had the same issue. Ok, now we have an opportunity to subscribe to several topics. But now I would like to subscribe to all topics only by one click. Is it possible to do?

**Comment by chkr1011** [comment]
Let me think about a proper solution. I will doing some prototypes how to implement this and keeping a proper UX.

**Comment by INTERNALINTERFERENCE** [comment]
I'd suggest to remove subscribe button. It will be better to subscribe to several topics by clicking connect button. For example, I have a list with 5 topics and I subscribe to all of them by clicking connect button
