### ISSUE TITLE
Sharing saved entries

### ISSUE THREAD

**Issue by seikosantana** [chkr1011/MQTTnetApp#41]
Hi, I was wondering if I can use the app as documentation tool so I can share my saved entries and have it loaded to another person's application instance.

Thanks in advance

**Comment by chkr1011** [comment]
This is a good idea. I will create a branch and start with that feature. As soon as this is working I will let you know.

**Comment by seikosantana** [comment]
Cool! Thanks for the great app and the effort. I enjoy working with it.

**Comment by chkr1011** [comment]
So you mean Sending or receiving payload

**Comment by seikosantana** [comment]
I actually meant this entry
![image](https://user-images.githubusercontent.com/35630407/163722010-32c28cfb-edf5-4102-b2b7-4bdbf90d8200.png)

Imagining something like postman's that can highlight the body as JSON. It even has kind of autocomplete to help typing the JSON, don't know if it is too far or irrelevant.
![image](https://user-images.githubusercontent.com/35630407/163722071-5d5fcd14-d416-48a6-8fa8-76c500da36b4.png)

On the sending part is more needed for me since I do try publishing JSONs a lot with MQTTnetApp.

**Comment by chkr1011** [comment]
@seikosantana Export and Import will be part of next version 1.6. Please create another ticket for the rich editor of JSON payloads etc.
