### ISSUE TITLE
Allow self signed certificates

### ISSUE THREAD

**Issue by msavara** [chkr1011/MQTTnetApp#47]
Hello, is it possible to add a function that would allow to use a non-valid certificate ( self signed ) on a checkbox?

**Comment by chkr1011** [comment]
This is a good feature idea. I will add it soon.

**Comment by chkr1011** [comment]
Is it possible for you to test the branch which is linked with this ticket?

**Comment by msavara** [comment]
> Is it possible for you to test the branch which is linked with this ticket?

It doesn't work. 
The server returned status code '404' when status code '101' was expected.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '404' when status code '101' was expected.

**Comment by msavara** [comment]
Yes :) looks okay :)

**Comment by msavara** [comment]
> Is it possible for you to test the branch which is linked with this ticket?

sure :)
