### ISSUE TITLE
how to access mqtt broker using token

### ISSUE THREAD

**Issue by moayyaed** [chkr1011/MQTTnetApp#49]
is there any option to access the mqtt broker by ACCESS_TOKEN?

example : I'm using to following command to publish message for my mqtt broker
mosquitto_pub -d -q 1 -h "$HOST_NAME" -p "1883" -t "temperature/sensor" -u "$ACCESS_TOKEN" -m {"temperature":25}

**Comment by chkr1011** [comment]
The man page of _mosquitto_pub_ describes that the parameter "-u" is used as the username. So you have to fill the access token in the username field of this app.
