### ISSUE TITLE
Save and restore payload

### ISSUE THREAD

**Issue by dagophil** [chkr1011/MQTTnetApp#50]
Hello,
thank you for this great app.
I am using the MQTTnetApp to send test messages to an application I am developing. It is great that the topics and their settings are saved and restored when restarting the MQTTnetApp. However, the payload is not restored and always clean after restart. Is this on purpose? Would it be possible to save and restore the payload as well?
Best regards, Philip

**Comment by chkr1011** [comment]
Thanks for reporting this issue. The payload is indeed missing in the state export. I will add it accordingly.

**Comment by dagophil** [comment]
That's great news, thank you :)
